root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  poll = true
  poll_interval = 0
  run_after_build = "chmod +x main"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false
  level = "debug"

[misc]
  clean_on_exit = false

[screen]
  keep_scroll = true
